export default {
  tutorialSidebar: [
    'the-nature-and-nurture-of-human-cooperation',
    {
      type: 'category',
      label: 'Cooperation in Perspective',
      link: { type: 'doc', id: 'cooperation-in-perspective/cooperation-in-perspective' },
      items: [
        'cooperation-in-perspective/human-behavior-in-general/human-behavior-in-general',
        'cooperation-in-perspective/what-is-cooperation/what-is-cooperation',
        'cooperation-in-perspective/what-is-adversarial-behavior/what-is-adversarial-behavior',
      ],
    },
    {
      type: 'category',
      label: 'Evolved Cooperation',
      link: { type: 'doc', id: 'evolved-cooperation/evolved-cooperation' },
      collapsed: false,
      items: [
        'evolved-cooperation/spatial-altruism/spatial-altruism',
        'evolved-cooperation/cooperative-hunting/cooperative-hunting',
      ],
    },
    {
      type: 'category',
      label: 'Learned Cooperation',
      link: { type: 'doc', id: 'learned-cooperation/learned-cooperation' },
      collapsed: false,
      items: [
        {
          type: 'category',
          label: "Prisoner's Dilemma",
          link: { type: 'doc', id: 'learned-cooperation/prisoners-dilemma/prisoners-dilemma' },
          collapsed: false,
          items: [],
        },
        {
          type: 'category',
          label: "Repeated Prisoner's Dilemma",
          link: { type: 'doc', id: 'learned-cooperation/repeated-prisoners-dilemma/repeated-prisoners-dilemma' },
          collapsed: false,
          items: [
            'learned-cooperation/repeated-prisoners-dilemma/ppo-study',
          ],
        },
      ],
    },
    { type: 'autogenerated', dirName: 'learning-selection-interaction' },
    {
      type: 'category',
      label: 'Archive',
      link: { type: 'doc', id: 'archive/archive-overview' },
      items: [
        {
          type: 'category',
          label: 'Human Behavior Patterns',
          items: [
            { type: 'autogenerated', dirName: 'archive/human-behavior-patterns/fundamentals' },
            { type: 'autogenerated', dirName: 'archive/human-behavior-patterns/machinery' },
            { type: 'autogenerated', dirName: 'archive/human-behavior-patterns/predicting' },
          ],
        },
        { type: 'autogenerated', dirName: 'archive/pred-prey-grass' },
        { type: 'autogenerated', dirName: 'archive/social-behavior' },
      ],
    },
    'to_do',
  ],
};
