export default {
  tutorialSidebar: [
    'the-nature-and-nurture-of-cooperation',
    {
      type: 'category',
      label: 'Cooperation in Perspective',
      link: { type: 'doc', id: 'cooperation-in-perspective/cooperation-in-perspective' },
      items: [
        'cooperation-in-perspective/human-behavior-in-general/human-behavior-in-general',
        'cooperation-in-perspective/what-is-cooperation',
      ],
    },
    { type: 'doc', id: 'evolved-cooperation/evolved-cooperation', label: 'Evolved Cooperation' },
    { type: 'doc', id: 'learned-cooperation/theory', label: 'Learned Cooperation' },
    { type: 'autogenerated', dirName: 'learning-selection-interaction' },
    {
      type: 'category',
      label: 'Archive',
      link: { type: 'doc', id: 'archive/archive-overview' },
      items: [
        {
          type: 'category',
          label: 'Human Behavior Patterns',
          items: [
            { type: 'autogenerated', dirName: 'archive/human-behavior-patterns/fundamentals' },
            { type: 'autogenerated', dirName: 'archive/human-behavior-patterns/machinery' },
            { type: 'autogenerated', dirName: 'archive/human-behavior-patterns/predicting' },
          ],
        },
        { type: 'autogenerated', dirName: 'archive/pred-prey-grass' },
        { type: 'autogenerated', dirName: 'archive/social-behavior' },
      ],
    },
    'to_do',
  ],
};
