export default {
  tutorialSidebar: [
    'index',
    {
      type: 'category',
      label: 'Cooperation in Perspective',
      link: { type: 'doc', id: 'cooperation-in-perspective' },
      items: ['archive/human-behavior-patterns/overview-hbp'],
    },
    { type: 'autogenerated', dirName: 'learned-cooperation' },
    { type: 'autogenerated', dirName: 'selected-cooperation' },
    { type: 'autogenerated', dirName: 'learning-selection-interaction' },
    {
      type: 'category',
      label: 'Archive',
      link: { type: 'doc', id: 'archive/archive-overview' },
      items: [
        {
          type: 'category',
          label: 'Human Behavior Patterns',
          items: [
            { type: 'autogenerated', dirName: 'archive/human-behavior-patterns/fundamentals' },
            { type: 'autogenerated', dirName: 'archive/human-behavior-patterns/machinery' },
            { type: 'autogenerated', dirName: 'archive/human-behavior-patterns/predicting' },
          ],
        },
        { type: 'autogenerated', dirName: 'archive/pred-prey-grass' },
        { type: 'autogenerated', dirName: 'archive/social-behavior' },
      ],
    },
    'to_do',
  ],
};
